### ISSUE TITLE
Theme pages

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/themia.co#5]
Each page should have their own page to access and unique url. 

For example: `themia.co/category/theme-name`

**Comment by mhammerc** [comment]
What to show on these pages ? The title, images, description, links (preview & download), category name, what else ?

**Comment by shtefcs** [comment]
All you mention + SEO things which is related to https://github.com/vanila-io/themia.co/issues/6.

Just display it in basic and @jelenajjo will do the rest regarding UI/frontend.

**Comment by mhammerc** [comment]
oki good :)

**Comment by mhammerc** [comment]
Okay, that's done. As said, need some front end work and i have to work on SEO.
However, we need to test this on the real website ! And if this seem to be successful, i will close the issue ofc

**Comment by mhammerc** [comment]
Note that i introduce something new. I call it the canonical name, it's the name of the theme showed in the url. By example, if a theme is named 'Flat theme', the cannonical name may be 'flat-theme'.
You have to define this canonical name inside the settings of each theme before using the new feature and access to the full page of each themes.
To access to the theme page, you have just to click on the theme name in the boxes.

**Comment by mhammerc** [comment]
(same for categories now since 160635c)

**Comment by shtefcs** [comment]
Closing, its works !
