### ISSUE TITLE
SEO - Search Engine Optimization :)

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/themia.co#6]
- [x] Dynamic Titles & Description
- [x] App routes `themia.co/category/theme-name`
- [x] OG (Open Graph)
- [x] Schema.org
- [x] Twitter Card
- [x] Sitemap

**Comment by naquiuddin** [comment]
I am using this https://github.com/DerMambo/ms-seo explained well at http://www.manuel-schoebel.com/blog/meteor-and-seo

**Comment by mhammerc** [comment]
everything implemented, need some tests now :)
