### ISSUE TITLE
Markdown editor for description field

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/themia.co#7]
Need **Markdown** editor for `Description` field

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/b2f6fe47-a966-4a26-aa80-8018ab009c59/2015-11-22_1010.png)

**Comment by naquiuddin** [comment]
Adding summernote instead of markdown editor. Because there isn't a markdown editor available for orionjs right now.

**Comment by shtefcs** [comment]
@martin-mh can u enable some editor for description field in creating themes ?

**Comment by mhammerc** [comment]
Yes i'm looking at it

**Comment by mhammerc** [comment]
Need to verify you like it and it work before closing !
