### ISSUE TITLE
Display category on front end

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/themia.co#8]
Display category in front-end boxes of each themes

**Comment by mhammerc** [comment]
Need testing on the real website (on meteor.com), then we will close the issue

**Comment by shtefcs** [comment]
Ok, @jelenajjo can deploy on http://themia1.meteor.com so we can test

**Comment by mhammerc** [comment]
Can we close it ?

**Comment by shtefcs** [comment]
lets ask @jelenajjo if she can do that alone.

**Comment by mhammerc** [comment]
do what, i've fixed the issue, no ?

**Comment by shtefcs** [comment]
oh, my bad, messed something :dancer:
